### ISSUE TITLE
Program giving wrong answer

### ISSUE THREAD

**Issue by robr345** [unartic/nxtBasic#2]
Hi, I've been trying out a program that uses the MOD statment. I've got an almost identical program working elsewhere that gives the correct answer nxtBasic does not.

nxtBasic result -78976 correct answer 233168 example program in nxtbasic-usagi.bas

A version that gives the correct answer written in VAX basic is in usagi.bas

there is also another problem that I have found if a THEN statment is on a seperate line the compilier gives an error, I have included an example as nxtbasic-usagi-error.bas

I have chaged the extension of the files to txt because github is silly.

[nxtbasic-usagi-error.txt](https://github.com/user-attachments/files/17268836/nxtbasic-usagi-error.txt)
[nxtbasic-usagi.txt](https://github.com/user-attachments/files/17268835/nxtbasic-usagi.txt)
[usagi.txt](https://github.com/user-attachments/files/17268838/usagi.txt)

**Comment by unartic** [comment]
Thanks for your report. Lets dive into them:

The default numeric var type is signed16bit int. Which means it has a value range of -32.768 to 32.767. So it is not able to count up to 233168. 

You can however dim ANS as float like this:

`
DIM ANS as float
CNT = 0
OPA = 0
ANS = 0
FOR CNT = 0 TO 999
	OPA = CNT MOD 3
	IF OPA = 0 THEN
		ANS = ANS + CNT
	ELSE
		OPA = CNT MOD 5
		IF OPA = 0 THEN
			ANS = ANS + CNT
		END IF
	END IF
NEXT CNT

PRINT ANS
`

Then it will be slower as it is using floating points, but will give you the answer you expect.

About the THEN being on a seperate line: that is simply not allowed :-) So the correct way of setting up an if statement in nxtBasic is:

IF (condition) THEN {do something}

or

IF (condition) THEN
  {do something}
END IF

**Comment by robr345** [comment]
Thank you for your quick answer.
